name: tray_manager
description: This plugin allows Flutter desktop apps to defines system tray.
version: 0.2.1
homepage: https://github.com/leanflutter/tray_manager

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  menu_base: ^0.1.0
  path: ^1.8.0
  shortid: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: TrayManagerPlugin
      windows:
        pluginClass: TrayManagerPlugin
